executors:
  node:
    docker:
      - image: circleci/node:14
aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn


version: 2.1

jobs:
  test:
    executor: node
    steps:
      
  build:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Build
          command: npm run start

orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
     - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - build
          requires:
            - test  
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main

